apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "freshrss.fullname" . }}-apache-health-bypass
  labels:
    {{- include "freshrss.labels" . | nindent 4 }}
data:
  zzz-health-bypass.conf: |
    <Location "/healthz">
        AuthType none
        Require all granted
    </Location>