{{- if .Values.traefik.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "monetr.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monetr.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- toYaml .Values.traefik.ingressRoute.entryPoints | nindent 4 }}
  routes:
    - match: Host(`{{ .Values.traefik.ingressRoute.host }}`) && PathPrefix(`/`)
      kind: Rule
      {{- if .Values.traefik.ingressRoute.middlewares }}
      middlewares:
        {{- range .Values.traefik.ingressRoute.middlewares }}
        - name: {{ .name }}
          {{- if .namespace }}
          namespace: {{ .namespace }}
          {{- end }}
        {{- end }}
      {{- end }}
      services:
        - name: {{ include "monetr.fullname" . }}
          port: {{ .Values.service.port }}
          scheme: http
  {{- if .Values.traefik.ingressRoute.tls.enabled }}
  tls:
    {{- if .Values.traefik.ingressRoute.tls.secretName }}
    secretName: {{ .Values.traefik.ingressRoute.tls.secretName | quote }}
    {{- end }}
  {{- end }}
{{- end }}
