apiVersion: v1
kind: Service
metadata:
  name: {{ include "monetr.fullname" . }}
  labels:
    {{- include "monetr.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "monetr.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
