apiVersion: v2
name: homepage
description: Self-managed chart for gethomepage/homepage (Traefik + Cloudflared friendly)
type: application
version: 0.1.1
appVersion: "v2.1.2"
home: https://github.com/gethomepage/homepage/releases
