apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trek.fullname" . }}-config
  labels:
    {{- include "trek.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
data:
{{- $data := dict -}}
{{- range $k, $v := .Values.config -}}
{{- if and (ne $k "extraEnv") (ne (toString $v) "") -}}
{{- $_ := set $data $k (toString $v) -}}
{{- end -}}
{{- end -}}
{{- range $k, $v := .Values.config.extraEnv -}}
{{- $_ := set $data $k (toString $v) -}}
{{- end -}}
{{- toYaml $data | nindent 2 }}

