{{- if and .Values.persistence.enabled (not .Values.persistence.data.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "trek.fullname" . }}-data
  labels:
    {{- include "trek.labels" . | nindent 4 }}
    app.kubernetes.io/component: data
  {{- with .Values.persistence.data.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  storageClassName: {{ .Values.persistence.data.storageClassName | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
{{- end }}
---
{{- if and .Values.persistence.enabled (not .Values.persistence.uploads.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "trek.fullname" . }}-uploads
  labels:
    {{- include "trek.labels" . | nindent 4 }}
    app.kubernetes.io/component: uploads
  {{- with .Values.persistence.uploads.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  storageClassName: {{ .Values.persistence.uploads.storageClassName | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.uploads.size | quote }}
{{- end }}

