replicaCount: 1

nameOverride: ""
fullnameOverride: "affine"

image:
  repository: ghcr.io/toeverything/affine
  tag: "stable"
  pullPolicy: IfNotPresent

waitImage:
  repository: busybox
  tag: "1.36.1"
  pullPolicy: IfNotPresent

secrets:
  existingSecret: affine-secrets-app

config:
  externalUrl: https://docs.nserbin.com
  host: docs.nserbin.com
  https: "true"
  port: "3010"
  deploymentType: selfhosted
  storagePath: /root/.affine/storage
  configPath: /root/.affine/config
  extraEnv: {}

postgres:
  image:
    repository: pgvector/pgvector
    tag: "pg16"
    pullPolicy: IfNotPresent
  service:
    port: 5432
  persistence:
    enabled: true
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    size: 10Gi
  resources:
    requests:
      cpu: 75m
      memory: 192Mi
    limits:
      cpu: 750m
      memory: 768Mi

redis:
  image:
    repository: redis
    tag: "7-alpine"
    pullPolicy: IfNotPresent
  service:
    port: 6379
  persistence:
    enabled: true
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    size: 1Gi
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi

persistence:
  storage:
    enabled: true
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    size: 10Gi

service:
  type: ClusterIP
  port: 80
  targetPort: 3010

serviceAccount:
  create: true
  name: ""
  automount: false

podSecurityContext:
  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL

resources:
  requests:
    cpu: 250m
    memory: 768Mi
  limits:
    cpu: 1500m
    memory: 2Gi

traefik:
  ingressRoute:
    enabled: true
    entryPoints:
      - web
    host: docs.nserbin.com
    middlewares: []
    tls:
      enabled: false
      secretName: ""

nodeSelector: {}
tolerations: []
affinity: {}
