apiVersion: v2
name: vault-wrapper
description: Wrapper chart to deploy HashiCorp Vault via official hashicorp/vault chart
type: application
version: 0.1.0

dependencies:
  - name: vault
    version: 1.3.0 # ejemplo; fijalo a una versión concreta
    repository: "https://helm.releases.hashicorp.com"
