vault:

  global:
    enabled: true

  ui:
    enabled: true
    serviceType: ClusterIP

  server:
    standalone:
      enabled: false

    ha:
      enabled: true
      replicas: 1

      raft:
        enabled: true
        setNodeId: true
        config: |
          ui = true

          listener "tcp" {
            address     = "0.0.0.0:8200"
            tls_disable = 1
          }

          storage "raft" {
            path = "/vault/data"
          }

          service_registration "kubernetes" {}

    dataStorage:
      enabled: true
      size: 8Gi
      mountPath: /vault/data

  injector:
    enabled: false

  csi:
    enabled: false

traefik:
  enabled: true

  ingressRoute:
    name: vault
    entryPoints:
      - web
    host: secrets.nserbin.com
    pathPrefix: /
    service:
      name: vault-ui
      port: 8200
      scheme: http

    middlewares:
      enabled: true
      chain:
        - vault-default-chain

  middlewares:
    securityHeaders:
      enabled: true
      stsSeconds: 31536000
      stsIncludeSubdomains: true
      stsPreload: true
      contentTypeNosniff: true
      browserXssFilter: true
      frameDeny: true
      referrerPolicy: "no-referrer"

    rateLimit:
      enabled: true
      average: 50
      burst: 100

    ipAllowList:
      enabled: false
      sourceRange:
        - 1.2.3.4/32

monitoring:
  enabled: true
  serviceMonitor:
    name: vault
    interval: 30s
    scrapeTimeout: 10s
    scheme: http
    portName: http
    path: /v1/sys/metrics

    selectorLabels:
      app.kubernetes.io/name: vault

    labels:
      release: kube-prometheus-stack


vaultAuth:
  serviceAccountName: vault-auth
  clusterRoleBindingName: vault-auth-tokenreview