apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "colanode.fullname" . }}-config
  labels:
    {{- include "colanode.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "name": {{ .Values.config.name | quote }},
      "web": {
        "domain": {{ .Values.config.domain | quote }}
      },
      "mode": "standalone",
      "cors": {
        "origin": {{ .Values.config.origin | quote }},
        "maxAge": 7200
      },
      "account": {
        "verificationType": {{ .Values.config.account.verificationType | quote }},
        "otpTimeout": {{ .Values.config.account.otpTimeout }},
        "google": {
          "enabled": false,
          "clientId": "env://ACCOUNT_GOOGLE_CLIENT_ID?",
          "clientSecret": "env://ACCOUNT_GOOGLE_CLIENT_SECRET?"
        }
      },
      "postgres": {
        "url": "env://POSTGRES_URL"
      },
      "redis": {
        "url": "env://REDIS_URL",
        "db": 0,
        "eventsChannel": "events"
      },
      "storage": {
        "tus": {
          "locker": {
            "type": "redis",
            "prefix": "colanode:tus:lock"
          },
          "cache": {
            "type": "none"
          }
        },
        "provider": {
          "type": "file",
          "directory": {{ .Values.config.storageDirectory | quote }}
        }
      },
      "email": {
        "enabled": false,
        "from": {
          "email": "colanode@nserbin.com",
          "name": "Colanode"
        },
        "provider": {
          "type": "smtp",
          "host": "env://EMAIL_SMTP_HOST?",
          "port": 587,
          "secure": false,
          "auth": {
            "user": "env://EMAIL_SMTP_USER?",
            "password": "env://EMAIL_SMTP_PASSWORD?"
          }
        }
      },
      "jobs": {
        "queue": {
          "name": "jobs",
          "prefix": "colanode"
        },
        "nodeUpdatesMerge": {
          "enabled": false,
          "cron": "0 5 */2 * * *",
          "batchSize": 500,
          "mergeWindow": 3600,
          "cutoffWindow": 7200
        },
        "documentUpdatesMerge": {
          "enabled": false,
          "cron": "0 5 */2 * * *",
          "batchSize": 500,
          "mergeWindow": 3600,
          "cutoffWindow": 7200
        },
        "cleanup": {
          "enabled": false,
          "cron": "0 5 */2 * * *"
        }
      },
      "workspace": {
        "maxFileSize": {{ .Values.config.workspace.maxFileSize | quote }}
      },
      "logging": {
        "level": {{ .Values.config.logging.level | quote }}
      }
    }
