{{- if .Values.postgres.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cal-diy.postgresName" . }}-data
  labels:
    {{- include "cal-diy.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    {{- toYaml .Values.postgres.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size | quote }}
  {{- if .Values.postgres.persistence.storageClassName }}
  storageClassName: {{ .Values.postgres.persistence.storageClassName | quote }}
  {{- end }}
---
{{- end }}
{{- if .Values.redis.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cal-diy.redisName" . }}-data
  labels:
    {{- include "cal-diy.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  accessModes:
    {{- toYaml .Values.redis.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size | quote }}
  {{- if .Values.redis.persistence.storageClassName }}
  storageClassName: {{ .Values.redis.persistence.storageClassName | quote }}
  {{- end }}
{{- end }}
