{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: crowdsec-postgres
  ports:
    - name: postgres
      port: {{ .Values.postgresql.port }}
      targetPort: postgres
{{- end }}
