{{- $csb := (.Values.crowdsecBouncer | default dict) -}}
{{- if ($csb.enabled | default false) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crowdsec-traefik-bouncer
  namespace: traefik
spec:
  replicas: {{ .Values.crowdsecBouncer.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: crowdsec-traefik-bouncer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: crowdsec-traefik-bouncer
    spec:
      containers:
        - name: bouncer
          image: "{{ .Values.crowdsecBouncer.image.repository }}:{{ .Values.crowdsecBouncer.image.tag }}"
          imagePullPolicy: {{ .Values.crowdsecBouncer.image.pullPolicy }}
          env:
            - name: CROWDSEC_BOUNCER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.crowdsecBouncer.secrets.existingSecret }}
                  key: {{ .Values.crowdsecBouncer.secrets.keyField }}
            - name: CROWDSEC_AGENT_HOST
              value: {{ .Values.crowdsecBouncer.crowdsecAgentHost | quote }}
            - name: CROWDSEC_BOUNCER_SCHEME
              value: {{ .Values.crowdsecBouncer.crowdsecBouncerScheme | quote }}
            - name: CROWDSEC_BOUNCER_LOG_LEVEL
              value: {{ .Values.crowdsecBouncer.logLevel | quote }}
            - name: CROWDSEC_BOUNCER_BAN_RESPONSE_CODE
              value: {{ .Values.crowdsecBouncer.banResponseCode | quote }}
            - name: CROWDSEC_BOUNCER_BAN_RESPONSE_MSG
              value: {{ .Values.crowdsecBouncer.banResponseMsg | quote }}
            - name: HEALTH_CHECKER_TIMEOUT_DURATION
              value: {{ .Values.crowdsecBouncer.healthCheckTimeout | quote }}
            - name: PORT
              value: {{ .Values.crowdsecBouncer.port | quote }}
            - name: GIN_MODE
              value: {{ .Values.crowdsecBouncer.ginMode | quote }}
            - name: TRUSTED_PROXIES
              value: {{ .Values.crowdsecBouncer.trustedProxies | quote }}
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /api/v1/ping
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /api/v1/healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
{{ toYaml .Values.crowdsecBouncer.resources | indent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
{{- end }}
