{{- $csb := (.Values.crowdsecBouncer | default dict) -}}
{{- $middleware := ($csb.middleware | default dict) -}}
{{- if and ($csb.enabled | default false) ($middleware.enabled | default false) }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $middleware.name | default "crowdsec-bouncer" }}
  namespace: traefik
spec:
  forwardAuth:
    address: http://crowdsec-traefik-bouncer.traefik.svc.cluster.local:8080/api/v1/forwardAuth
    trustForwardHeader: true
{{- end }}
