apiVersion: v1
kind: Service
metadata:
  name: {{ include "terraform-shared-backend.fullname" . }}
  labels:
    {{- include "terraform-shared-backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "terraform-shared-backend.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "terraform-shared-backend.fullname" . }}-headless
  labels:
    {{- include "terraform-shared-backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  clusterIP: None
  selector:
    {{- include "terraform-shared-backend.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
