apiVersion: v2
name: yopass
description: YoPass exposed via Traefik IngressRoute
type: application
version: 0.1.0
appVersion: "14.1.0"
home: https://github.com/jhaals/yopass/releases
sources:
  - https://github.com/jhaals/yopass
