{{- if and .Values.stores.enabled .Values.stores.clusterSecretStores }}
{{- range .Values.stores.clusterSecretStores }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .name }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: {{ .syncWave | default 1 | quote }}
    argocd.argoproj.io/ignore-healthcheck: "true"
spec:
  provider:
{{- toYaml .provider | nindent 4 }}
---
{{- end }}
{{- end }}
