{{- if and .Values.stores.enabled .Values.stores.secretStores }}
{{- range .Values.stores.secretStores }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default "tools" }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
{{- toYaml .provider | nindent 4 }}
---
{{- end }}
{{- end }}
