{{- if .Values.postgres.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "paperless-ngx.postgresName" . }}-data
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    {{- toYaml .Values.postgres.persistence.accessModes | nindent 4 }}
  storageClassName: {{ .Values.postgres.persistence.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size | quote }}
{{- end }}
---
{{- if .Values.redis.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "paperless-ngx.redisName" . }}-data
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  accessModes:
    {{- toYaml .Values.redis.persistence.accessModes | nindent 4 }}
  storageClassName: {{ .Values.redis.persistence.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size | quote }}
{{- end }}
---
{{- range $name, $pvc := .Values.persistence }}
{{- if $pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "paperless-ngx.fullname" $ }}-{{ $name }}
  labels:
    {{- include "paperless-ngx.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  accessModes:
    {{- toYaml $pvc.accessModes | nindent 4 }}
  storageClassName: {{ $pvc.storageClassName | quote }}
  resources:
    requests:
      storage: {{ $pvc.size | quote }}
---
{{- end }}
{{- end }}
