apiVersion: v2
name: crowdsec
description: Wrapper chart (official CrowdSec chart + local PostgreSQL + ExternalSecret + Traefik IngressRoute)
type: application
version: 0.2.0
appVersion: "1.7.7"

dependencies:
  - name: crowdsec
    repository: "https://crowdsecurity.github.io/helm-charts"
    version: "0.20.1"
