replicaCount: 1

image:
  repository: ghcr.io/linkwarden/linkwarden
  tag: "v2.14.1"
  pullPolicy: IfNotPresent

service:
  enabled: true
  type: ClusterIP
  port: 3000

ingressRoute:
  enabled: true
  entryPoints: [web]
  host: bookmarks.nserbin.com
  pathPrefix: /
  tls:
    enabled: false
    secretName: ""
  middlewares: []


config:
  nextauthUrl: ""  # If Empty => https://<host>/api/v1/auth
  extraEnv:
    CUSTOM_OPENAI_BASE_URL: "https://generativelanguage.googleapis.com/v1beta"
    CUSTOM_OPENAI_NAME: "gemini"
    #OPENAI_MODEL: "gemini-3-flash-preview"
    OPENAI_MODEL: "gemini-2.5-flash-lite"

secrets:
  appSecretName: linkwarden-secrets-app
  dbSecretName: linkwarden-secrets-db


authentik:
  enabled: true
  customName: "Authentik"

persistence:
  enabled: true
  storageClassName: ""
  accessModes: ["ReadWriteOnce"]
  size: 5Gi

postgres:
  enabled: true
  image:
    repository: postgres
    tag: "16-alpine"
    pullPolicy: IfNotPresent
  persistence:
    enabled: true
    storageClassName: ""
    accessModes: ["ReadWriteOnce"]
    size: 2Gi
  service:
    enabled: true
    port: 5432

meilisearch:
  enabled: true
  image:
    repository: getmeili/meilisearch
    tag: v1.33.1
    pullPolicy: IfNotPresent
  persistence:
    enabled: true
    storageClassName: ""
    accessModes: ["ReadWriteOnce"]
    size: 5Gi
  service:
    enabled: true
    port: 7700

externalDatabase:
  enabled: false

ollama:
  enabled: false

  image:
    repository: ollama/ollama
    tag: latest
    pullPolicy: IfNotPresent

  service:
    enabled: true
    type: ClusterIP
    port: 11434

  persistence:
    enabled: false
    storageClassName: ""
    accessModes: ["ReadWriteOnce"]
    size: 15Gi   # bajar a 10Gi

  # IMPORTANTÍSIMO: sin auto-pull
  modelPull:
    enabled: false
    model: "phi3:mini-4k"

  # Límites LOW-RAM
  resources:
    requests:
      cpu: "100m"
      memory: 512Mi
      ephemeral-storage: "256Mi"
    limits:
      cpu: "1000m"
      memory: 2Gi
      ephemeral-storage: "1Gi"

  extraEnv:
    OLLAMA_NUM_PARALLEL: "1"
    OLLAMA_MAX_LOADED_MODELS: "1"
