{{- if .Values.chrome.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "karakeep.fullname" . }}-chrome
  labels:
    {{- include "karakeep.labels" . | nindent 4 }}
    app.kubernetes.io/component: chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "karakeep.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: chrome
  template:
    metadata:
      labels:
        {{- include "karakeep.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: chrome
    spec:
      dnsPolicy: {{ .Values.chrome.dnsPolicy }}
      {{- with .Values.chrome.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: chrome
          image: "{{ .Values.chrome.image.repository }}:{{ .Values.chrome.image.tag }}"
          imagePullPolicy: {{ .Values.chrome.image.pullPolicy }}
          {{- with .Values.chrome.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{ end }}
          {{- $chromeArgs := list "--headless" "--no-sandbox" "--disable-gpu" "--disable-dev-shm-usage" (printf "--remote-debugging-address=%s" "0.0.0.0") (printf "--remote-debugging-port=%d" (.Values.chrome.service.port | int)) "--hide-scrollbars" -}}
          {{- $chromeArgs = concat $chromeArgs .Values.chrome.extraArgs -}}
          command:
            {{- toYaml .Values.chrome.command | nindent 12 }}
            {{- range $chromeArgs }}
            - {{ . | quote }}
            {{- end }}
          ports:
            - name: debug
              containerPort: {{ .Values.chrome.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.chrome.resources | nindent 12 }}
{{- end }}
