external-secrets:
  installCRDs: true

  serviceAccount:
    create: true
    name: external-secrets

stores:
  enabled: true
  secretStores: []

  clusterSecretStores:
    - name: vault
      syncWave: 1
      provider:
        vault:
          server: "http://vault.tools.svc.cluster.local:8200"
          path: "kv"
          version: "v2"
          auth:
            kubernetes:
              mountPath: "kubernetes"
              role: "eso-k8s"
              serviceAccountRef:
                name: external-secrets
                namespace: tools


externalSecrets:
  enabled: true
  refreshInterval: 1h
  items:

    - name: cloudflared-secrets
      namespace: traefik
      secretStoreRef:
        name: vault
        kind: ClusterSecretStore
      target:
        name: cloudflared-secrets
        creationPolicy: Owner
        deletionPolicy: Retain
      data:
        - secretKey: credentials.json
          remoteRef:
            key: k8s/core/networking/cloudflare/credentials

    - name: authentik-secrets
      namespace: tools
      secretStoreRef:
        name: vault
        kind: ClusterSecretStore
      target:
        name: authentik-secrets
        creationPolicy: Owner
        deletionPolicy: Retain
      data:
        - secretKey: POSTGRES_DB
          remoteRef:
            key: k8s/core/security/authentik
            property: POSTGRES_DB
        - secretKey: POSTGRES_USER
          remoteRef:
            key: k8s/core/security/authentik
            property: POSTGRES_USER
        - secretKey: POSTGRES_PASSWORD
          remoteRef:
            key: k8s/core/security/authentik
            property: POSTGRES_PASSWORD
