apiVersion: v2
name: github-actions-runner
description: GitHub Actions Runner Controller with a managed runner scale set
type: application
version: 0.1.0
appVersion: "0.14.2"
home: https://github.com/actions/actions-runner-controller/releases
dependencies:
  - name: gha-runner-scale-set-controller
    alias: controller
    version: 0.14.2
    repository: oci://ghcr.io/actions/actions-runner-controller-charts
    condition: controller.enabled
  - name: gha-runner-scale-set
    alias: runnerScaleSet
    version: 0.14.2
    repository: oci://ghcr.io/actions/actions-runner-controller-charts
    condition: runnerScaleSet.enabled
  - name: gha-runner-scale-set
    alias: runnerScaleSetWithVars
    version: 0.14.2
    repository: oci://ghcr.io/actions/actions-runner-controller-charts
    condition: runnerScaleSetWithVars.enabled
