apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  project: default

  source:
    repoURL: "https://github.com/Nserbin/k3s-cluster-charts.git"
    targetRevision: "main"
    path: "charts/homepage"
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: "https://kubernetes.default.svc"
    namespace: tools

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
