apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mcp-gateway
  namespace: argocd
spec:
  revisionHistoryLimit: 5
  project: default

  source:
    repoURL: "https://github.com/NSerbin/k3s-cluster-charts.git"
    targetRevision: "main"
    path: "charts/mcp-gateway"
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: "https://kubernetes.default.svc"
    namespace: tools

  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: mcp-gateway-postgres
      namespace: tools
      jqPathExpressions:
        - .spec.persistentVolumeClaimRetentionPolicy
        - .spec.podManagementPolicy
        - .spec.revisionHistoryLimit
        - .spec.updateStrategy
        - .spec.volumeClaimTemplates[].spec.volumeMode
        - .spec.template.spec.dnsPolicy
        - .spec.template.spec.restartPolicy
        - .spec.template.spec.schedulerName
        - .spec.template.spec.terminationGracePeriodSeconds
        - .spec.template.spec.containers[].terminationMessagePath
        - .spec.template.spec.containers[].terminationMessagePolicy
        - .spec.template.spec.containers[].livenessProbe.successThreshold
        - .spec.template.spec.containers[].readinessProbe.successThreshold
    - group: apps
      kind: StatefulSet
      name: mcp-gateway-redis
      namespace: tools
      jqPathExpressions:
        - .spec.persistentVolumeClaimRetentionPolicy
        - .spec.podManagementPolicy
        - .spec.revisionHistoryLimit
        - .spec.updateStrategy
        - .spec.volumeClaimTemplates[].spec.volumeMode
        - .spec.template.spec.dnsPolicy
        - .spec.template.spec.restartPolicy
        - .spec.template.spec.schedulerName
        - .spec.template.spec.terminationGracePeriodSeconds
        - .spec.template.spec.containers[].terminationMessagePath
        - .spec.template.spec.containers[].terminationMessagePolicy
        - .spec.template.spec.containers[].livenessProbe.successThreshold
        - .spec.template.spec.containers[].readinessProbe.successThreshold

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
