apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "linkwarden.fullname" . }}-config
  labels:
    {{- include "linkwarden.labels" . | nindent 4 }}
data:
{{- $nextauth := default (printf "https://%s/api/v1/auth" .Values.ingressRoute.host) .Values.config.nextauthUrl -}}
{{- $data := dict "NEXTAUTH_URL" $nextauth -}}

{{- if .Values.authentik.enabled -}}
{{- $_ := set $data "NEXT_PUBLIC_AUTHENTIK_ENABLED" "true" -}}
{{- $_ := set $data "AUTHENTIK_CUSTOM_NAME" (.Values.authentik.customName | default "Authentik") -}}
{{- end -}}

{{- if .Values.ollama.enabled -}}
{{- $_ := set $data "NEXT_PUBLIC_OLLAMA_ENDPOINT_URL" (printf "http://%s-ollama:%d" (include "linkwarden.fullname" .) (.Values.ollama.service.port | int)) -}}
{{- $_ := set $data "OLLAMA_MODEL" (.Values.ollama.model | default "phi3:mini-4k") -}}
{{- end -}}

{{- range $k, $v := .Values.config.extraEnv -}}
{{- $_ := set $data $k (printf "%v" $v) -}}
{{- end -}}

{{- toYaml $data | nindent 2 }}
