apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "linkwarden.fullname" . }}-config
  labels:
    {{- include "linkwarden.labels" . | nindent 4 }}
data:
  NEXTAUTH_URL: {{- if .Values.config.nextauthUrl -}}{{ .Values.config.nextauthUrl | quote }}{{- else -}}{{ printf "https://%s/api/v1/auth" .Values.ingressRoute.host | quote }}{{- end }}

  {{- if .Values.authentik.enabled }}
  NEXT_PUBLIC_AUTHENTIK_ENABLED: "true"
  AUTHENTIK_CUSTOM_NAME: {{ .Values.authentik.customName | quote }}
  {{- end }}

  {{- range $k, $v := .Values.config.extraEnv }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
