apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "linkwarden.fullname" . }}
  labels:
    {{- include "linkwarden.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "linkwarden.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "linkwarden.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: linkwarden
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000

          envFrom:
            - configMapRef:
                name: {{ include "linkwarden.fullname" . }}-config
            - secretRef:
                name: {{ .Values.secrets.appSecretName }}
            - secretRef:
                name: {{ .Values.secrets.dbSecretName }}

          env:
            - name: DATABASE_URL
              {{- if .Values.postgres.enabled }}
              value: {{ printf "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@%s-postgres:%d/$(POSTGRES_DB)" (include "linkwarden.fullname" .) (.Values.postgres.service.port | int) | quote }}
              {{- else if .Values.externalDatabase.enabled }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.appSecretName }}
                  key: DATABASE_URL
              {{- else }}
              value: ""
              {{- end }}

            {{- if .Values.meilisearch.enabled }}
            - name: MEILI_HOST
              value: {{ printf "http://%s-meilisearch:%d" (include "linkwarden.fullname" .) (.Values.meilisearch.service.port | int) | quote }}
            {{- end }}

          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /data/data
            {{- end }}

      volumes:
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "linkwarden.fullname" . }}-data
        {{- end }}
