apiVersion: v2
name: colanode
description: Self-managed chart for Colanode workspace
type: application
version: 0.1.0
appVersion: "latest"
home: https://github.com/colanode/colanode
icon: https://github.com/colanode.png
sources:
  - https://github.com/colanode/colanode
