replicaCount: 1

nameOverride: ""
fullnameOverride: "colanode"

image:
  repository: ghcr.io/colanode/server
  tag: "latest"
  pullPolicy: IfNotPresent

waitImage:
  repository: busybox
  tag: "1.36.1"
  pullPolicy: IfNotPresent

secrets:
  existingSecret: colanode-secrets-app

config:
  name: "Colanode"
  domain: docs.nserbin.com
  origins:
    - https://docs.nserbin.com
    - https://app.colanode.com
    - https://eu.colanode.com
    - https://us.colanode.com
  configMountPath: /config.json
  storageDirectory: /var/lib/colanode/storage
  account:
    verificationType: automatic
    otpTimeout: 600
  workspace:
    maxFileSize: "524288000"
  logging:
    level: info

postgres:
  image:
    repository: ghcr.io/colanode/postgresql
    tag: "17"
    pullPolicy: IfNotPresent
  service:
    port: 5432
  persistence:
    enabled: true
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    size: 8Gi
  resources:
    requests:
      cpu: 75m
      memory: 192Mi
    limits:
      cpu: 750m
      memory: 768Mi

redis:
  image:
    repository: redis
    tag: "7-alpine"
    pullPolicy: IfNotPresent
  service:
    port: 6379
  persistence:
    enabled: true
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    size: 1Gi
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi

persistence:
  storage:
    enabled: true
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    size: 10Gi

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

serviceAccount:
  create: true
  name: ""
  automount: false

podSecurityContext:
  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL

resources:
  requests:
    cpu: 150m
    memory: 384Mi
  limits:
    cpu: 1000m
    memory: 1Gi

traefik:
  ingressRoute:
    enabled: true
    entryPoints:
      - web
    host: docs.nserbin.com
    middlewares: []
    tls:
      enabled: false
      secretName: ""

nodeSelector: {}
tolerations: []
affinity: {}
